//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.View.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medicines()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int id_medicines { get; set; }
        public string medicine_name { get; set; }
        public string medicine_code { get; set; }
        public Nullable<int> cost { get; set; }
        public string amount { get; set; }
        public string description { get; set; }
        public Nullable<int> sale_cost { get; set; }
        public Nullable<int> providers_id_providers { get; set; }
        public Nullable<int> medicines_photo_id_medicines_photo { get; set; }
    
        public virtual medicines_photo medicines_photo { get; set; }
        public virtual providers providers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
    }
}
