//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.View.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int id_orders { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> user_id_user { get; set; }
        public Nullable<int> customers_id_customers { get; set; }
        public string order_time { get; set; }
        public string order_sum { get; set; }
        public Nullable<int> adresses_id_adresses { get; set; }
        public Nullable<int> medecines_id_medecines { get; set; }
    
        public virtual adresses adresses { get; set; }
        public virtual customers customers { get; set; }
        public virtual medicines medicines { get; set; }
        public virtual user user { get; set; }
    }
}
